spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toutiao?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123
  velocity:
    cache: false
    suffix: .html
    toolbox-config-location: toolbox.xml
mybatis:
  config-location: classpath:mybatis-config.xml

