spring:
  profiles:
    active: online
  jpa:
    show-sql: true
---
spring:
  profiles: dev
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/monitor?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/monitor2?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 9090
---
spring:
  profiles: pre
  datasource:
    primary:
      url: jdbc:mysql://139.224.0.118:3306/mooctest_main?useUnicode=yes&characterEncoding=UTF-8
      username: root
      password: secr3t!0525
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://139.224.0.118:3306/webide?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
      username: root
      password: secr3t!0525
      driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: validate
server:
  port: 9090
---
spring:
  profiles: online
  datasource:
    primary:
      url: jdbc:mysql://114.55.91.83:3306/mooctest_main?useUnicode=yes&characterEncoding=UTF-8
      username: liuzicong
      password: secr3t!
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://114.55.91.83:3306/webide?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
      username: liuzicong
      password: secr3t!
      driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: validate
server:
  port: 9090









